version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "restaurante"
      POSTGRES_PASSWORD: "restaurante@123"
      POSTGRES_DB: "restaurantedb"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - docker-network
    restart: always

  project-restaurante:
    container_name: project-restaurante
    image: project-restaurante:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: qa
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge