FROM amazoncorretto:11-alpine-jdk as builder
WORKDIR /app
RUN apk add maven
COPY . .
RUN ls -l
RUN mvn clean package

FROM amazoncorretto:11-alpine
LABEL AUTHOR="Bruno Vinicius"
WORKDIR /app
COPY --from=builder /app/target/*.jar .
EXPOSE 8080
CMD ['java', '-jar', '/app/*.jar']